version: '3'
services:
  web:
    build: .
    ports:
      - 5000:5000
    # command: python app.py
    environment:
      - SCRIPT_NAME=/prism-heart
    command: gunicorn -b 0.0.0.0:5000 app:app
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    depends_on:
      - web
