version: '3'
services:
  web:
    build: .
    ports:
      - 5000:5000
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./static:/static
    depends_on:
      - web
